### PR TITLE
Fixes // appearing before auth token in npmrc

### LINKED ISSUE #59: npm-cli-login appends an extra / to the .npmrc file
Hi

When using npm-cli-login it appends an unexpected / to the .npmrc file before the auth token

### command
```
$REGISTRY=https://companyname.jfrog.io/artifactory/api/npm/node-packages/
npm-cli-login -u $USERNAME -p $PASSWORD -e $EMAIL -r $REGISTRY -s $SCOPE
```

### expected output
```
@companyname:registry=https://companyname.jfrog.io/artifactory/api/npm/node-packages/
//companyname.jfrog.io/artifactory/api/npm/node-packages/:_authToken=...
```
### actual output
```
@companyname:registry=https://companyname.jfrog.io/artifactory/api/npm/node-packages/
//companyname.jfrog.io/artifactory/api/npm/node-packages//:_authToken=...
```

The extra trailing slash breaks npm install and throws auth errors

### PR DESCRIPTION
**Pull request by ashwini-desai**
Fixes [this](https://github.com/postmanlabs/npm-cli-login/issues/59) issue

### CODE REVIEW

**Comment by ashwini-desai** [comment]
@kunagpal @xavier-villelegier @czardoz @madebysid : If anyone of you could have a look at the PR, that would be great.

**Comment by ashwini-desai** [comment]
@kunagpal @xavier-villelegier @czardoz @madebysid : Can one of you please review this PR?

**Comment by sdnts** [comment]
Hey I'm not really involved with this repo anymore, I'm guessing someone from Postman will need to take a look at this.

**Comment by ashwini-desai** [comment]
@abhijitkane @jviotti : Can one of you help reviewing this PR?

**Comment by czardoz** [comment]
Hi @ashwini-desai, thanks for the PR. As you can see, this package hasn't been updated since 2019 (and even that commit was not released on NPM IIRC). I'd be very cautious about shipping an update with outdated dependencies etc. 

I think a more quick approach for you would be to fork this package and publish it on NPM under a new name.

File: lib/login.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ module.exports = {
         }
 
         var authWrite = lines.findIndex(function (element, index, array) {
-            if ( element.indexOf(args.registry.slice(args.registry.search(/\:\/\//, '') + 1) +
+            if ( element.indexOf(args.registry.slice(args.registry.search(/\:\//, '') + 1) +
```
Comment (jviotti) [inline lib/login.js]: Would it be possible to extract this regex as a constant and re-use it in both cases, so its easier to spot and fix in one place rather than in two if we ever need to revise it again in the future?

**Review by jviotti — APPROVED** [review]

**Comment by czardoz** [comment]
Ah looks like @jviotti is here to help, perhaps my previous comment can be ignored :)

**Comment by jviotti** [comment]
@czardoz I have almost zero-context with regards to this module but happy to help in any way I can!

File: lib/login.js (hunk 1 above)
Comment (ashwini-desai) [reply lib/login.js]: @jviotti : Extracted a `const` to hold the regex pattern.

**Comment by ashwini-desai** [comment]
@jviotti : I have incorporated the changes

**Comment by jviotti** [comment]
@ashwini-desai PR merged. Let me see if I have access to publish a new version myself and I'll let you guys know here. Thanks a lot!

**Comment by ashwini-desai** [comment]
Thanks @jviotti . Can you please add `hacktoberfest-accepted` label?

**Comment by jviotti** [comment]
Done @ashwini-desai

**Comment by jviotti** [comment]
So this package is not released to NPM under the Postman namespace, so looks like we don't have access anymore (only the original contributors have). @czardoz I believe you were one of the original contributors. If so, can you give me access to this package on NPM? My NPM username is `jviotti`

**Comment by czardoz** [comment]
Done. I would _highly_ recommend releasing a new version only after updating the dependencies. It would also be important to release it as a breaking change (1.x).

**Comment by jviotti** [comment]
@ashwini-desai @czardoz I released v1.0.0 to npm. Some of the dependencies require major upgrades and I'm not confident about making such changes given I don't have much context about what this module is trying to do and the fact that the test suite fails for me even on `master`.

@ashwini-desai Feel free to send a PR upgrading the dependencies it if works for you and I'll publish another release.
